import Button from '@/components/Button';
import Head from 'next/head';
import { FC, ReactNode } from 'react';
import styled from 'styled-components';

interface CustomLinkProps {
  className?: string;
  children: ReactNode;
  href: string;
}

interface StyledCustomLinkProps extends CustomLinkProps {}

const Main = styled.main`
  display: grid;
  place-items: center;
  min-height: 100vh;
`;

const Intro = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const StyledCustomLink: FC<StyledCustomLinkProps> = ({ className, children, href }) => (
  <StyledLink href={href} className={className}>
    {children}
  </StyledLink>
);

const StyledLink = styled.a`
  display: block;
  padding: 12px 24px;
  border-radius: 100px;
  background: #000;
  color: #fff;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Grebban Puzzle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Intro>
          <h1>Grebban puzzle</h1>
          <Button href="/game">Let&apos;s play</Button>
        </Intro>
      </Main>
    </>
  );
}
